name = "Natureal"
author = "Encode42"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "789dffdfc5e9fdf960a1c81cae91ad1d94e937ba71d6ec35b3fd1800b04e9694"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
