name = "Natureal"
author = "Encode42"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c22828d0b9d6d8d3752f0130660f6b326ff7aa088f17ddd0ed80e217b59a884"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
