name = "Natureal"
author = "Encode42"
version = "1.1.2-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6a853fabd9fb2a3b39e9a4651208182c762d4cf00349847634e2a2eec732cfc"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
