name = "Natureal"
author = "Encode42"
version = "2.0.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d94acff381a5a323c6d3f70a70629ffe944055c81388b5a2279075253525c80"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
