name = "Natureal"
author = "Encode42"
version = "1.1.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc4922014db0fd1e30495c152f736b595bc22973e6fe83b7642738295cf0b75e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
