enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = true
cinderscapes = true
everycomp = true
farmersdelight = true
campanion = true
croptopia = true
pfm = true
betternether = true
brewery = true
morefrogs = true
variantcraftingtables = true
betterend = true
friendsandfoes = true
twigs = true
ecologics = true
lightestlamp = true
dramaticdoors = true
powah = true
byg = true
variant_grindstones = true
halfdoors = true
tokenablefurnaces = true
variant_bookshelves = true
minecarttweaks = true
wilderwild = true
variant_lanterns = true
modern_industrialization = true
deeperdarker = true
varietyaquatic = true
customportalapi = true
naturalist = true
enderscape = true
nightlights = true
botania = true
hibernalherbs = true
supplementaries = true
whocosmetics = true
variantcomposters = true
endrem = true
culinaryconstruct = true
bedspreads = true
chipped = true
clutter = true
llamarama = true
convenientdecor = true
tardis_refined = true
windchimes = true
extended_drawers = true
goodall = true
jmc = true
woof = true
vsas = true
angling = true
minecraft = true
philipsruins = true
qu-enchantments = true
ae2 = true
variantbarrels = true
waystones = true
creeperoverhaul = true
bodacious_berries = true
traverse = true
rocks = true
xercamusic = true
enchantinginfuser = true
expandeddelight = true
skylorlib = true
grapplemod = true
