name: Build
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.19"

    - name: Install packwiz
      run: |
        go install github.com/packwiz/packwiz@latest

    - name: Build
      run: |
        packwiz modrinth export

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Modrinth Pack
        path: |
          /Natureal-*.mrpack

