name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.19"

    - name: Install packwiz
      run: |
        go install github.com/packwiz/packwiz@latest

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: pnpm

    - name: Install dependencies
      run: |
        pnpm install

    - name: Build Modrinth pack
      run: |
        pnpm run export:modrinth

    - name: Upload Modrinth pack
      uses: actions/upload-artifact@v3
      with:
        name: Modrinth Pack
        path: |
          /build/*.mrpack

    - name: Build CurseForge pack
      run: |
        pnpm run export:curseForge

    - name: Upload CurseForge pack
      uses: actions/upload-artifact@v3
      with:
        name: CurseForge Pack
        path: |
          /build/*.cf.zip

    - name: Send webhook notification
      if: always()
      run: |
        git clone https://github.com/Encode42/discord-workflows-webhook.git webhook
        bash webhook/send.sh ${{ job.status }} ${{ secrets.WEBHOOK_URL }}
      shell: bash
