name: Publish

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the update."
        type: string
        required: true

      releaseChannel:
        description: "Release channel to release the mod pack in."
        type: choice
        options:
          - release
          - beta
          - alpha
        default: "release"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Set up Packwiz cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/packwiz/cache/
          key: ${{ runner.os }}-packwiz-store
          restore-keys: ${{ runner.os }}-packwiz-store

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --prod

      - name: Drop snapshot label
        id: version
        run: |
          sed -i 's/\(version = ".*\)-SNAPSHOT\("\)/\1\2/' src/pack/pack.toml
          echo "VERSION=$(cat src/pack/pack.toml | grep "version =" | sed 's/version = "\(.*\)"/\1/')" >> $GITHUB_OUTPUT

      - name: Build Modrinth pack
        run: pnpm run client:modrinth

      - name: Build CurseForge pack
        run: |
          pnpm run client:curseForge
          pnpm run server:curseForge

      - name: Get commits since last tag
        id: commits
        uses: simbo/changes-since-last-release-action@v1
        with:
          line-prefix: "- "
          include-hashes: false

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: ${{ steps.version.outputs.VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-prerelease: ${{ inputs.releaseChannel != 'release' }}

          modrinth-id: scFX3hJJ
          modrinth-token: ${{ secrets.MODRINTH_UPLOAD_TOKEN }}

          #curseforge-id: 867551
          #curseforge-token: ${{ secrets.CURSEFORGE_UPLOAD_TOKEN }}

          name: ${{ inputs.name != '' && inputs.name || steps.version.outputs.VERSION }}
          version: ${{ steps.version.outputs.VERSION }}
          version-type: ${{ inputs.releaseChannel }}
          loaders: fabric
          game-versions: 1.19.2

          github-files: |
            build/*.mrpack
            build/*.cf.zip
          modrinth-files: build/*.mrpack
          #curseforge-files: build/*.cf.zip
          changelog: ${{ steps.commits.outputs.log }}

          fail-mode: warn
