name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish the mod pack as."
        required: true
        type: string

      releaseChannel:
        description: "Release channel to release the mod pack in."
        type: choice
        options:
          - release
          - beta
          - alpha
        default: "release"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Setup Packwiz cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/packwiz/cache/
          key: ${{ runner.os }}-packwiz-store
          restore-keys: ${{ runner.os }}-packwiz-store

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: |
          ls ~/.cache/packwiz/cache/
          pnpm install --prod

      - name: Build Modrinth pack
        run: pnpm run export:modrinth

      - name: Build CurseForge pack
        run: pnpm run export:curseForge

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: scFX3hJJ
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          name: ${{ inputs.version }}
          version: ${{ inputs.version }}
          loaders: fabric
          game-versions: 1.19.2

          modrinth-files: build/*.mrpack
          changelog-file: changelog.md
